# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuns',
            name='image_src',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.TimeField(),
        ),
    ]
