# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_auto_20171010_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuns',
            name='image_src',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
